services:
  remnabot:
    image: ghcr.io/alexporteb/remnabot:main
    container_name: remnabot
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - remnawave-network

networks:
  remnawave-network:
    external: true
